#!/bin/bash -x 

#ubuntu/linux
#export QUARTUS="$HOME/intelFPGA_lite/18.1/quartus"
QUARTUS="$HOME/intelFPGA_lite/23.1std/quartus"
PATH="$QUARTUS/bin:$PATH"
QUESTA_HOME="$HOME/intelFPGA_lite/23.1std/questa_fse"
PATH="$QUESTA_HOME/bin:$PATH"
JAVA_HOME="$HOME/jdk1.6.0_45"
#JAVA_HOME="$HOME/jdk1.8.0_202"
PATH="$JAVA_HOME/bin:$PATH"

# P3=HelloWorld
# P3=LedSwitchPattern
# P3=MyApp
P3=SpiritLevel
# P3=SPIFlash

# msys2/windows
# export QUARTUS="/c/intelFPGA_lite/23.1lite/quartus"
# export JAVA_HOME="/c/Users/peter/jdk1.6.0_45"
# export PATH="$QUARTUS/bin64:$JAVA_HOME/bin:$PATH"

# java -version
# quartus_pgm -a

# gcc c_src/down_posix.c -o down
# gcc c_src/echo_posix.c -o e

# make clean 
# make directories
# make tools
# make jop_blink_test
# make jop_testmon

# make jopser && \
make japp
# make sim
# cd ghdl && ./run.sh 
# cd ..

# make jsim
# make japp P1=test P2=test P3=$P3 && minicom -b 460800 -o -D /dev/ttyUSB1

# cd quartus/max1000 && quartus_pgm -c Arrow-USB-Blaster -m JTAG jop.cdf
# cd ../..
# ./down -e -usb java/target/dist/bin/$P3.jop /dev/ttyUSB2
# ./down -usb java/target/dist/bin/$P3.jop /dev/ttyUSB1 && \
# minicom -b 460800 -o -D /dev/ttyUSB1

