#!/bin/bash

#export QUARTUS="$HOME/intelFPGA_lite/18.1/quartus"
export QUARTUS="$HOME/intelFPGA_lite/23.1std/quartus"
export JAVA_HOME="$HOME/jdk1.6.0_45"
#export JAVA_HOME="$HOME"/jdk1.8.0_202"
export PATH="$QUARTUS/bin:$JAVA_HOME/bin:$PATH"

#make clean
#make directories
#make tools
#make jop_blink_test
#make jop_testmon
#make jopser
make japp
#make jsim
#make japp −e P1=bench P2=jbe P3=DoAll
#make japp −e P1=test P2=test P3=HelloWorld
#make japp −e P1=test P2=test P3=LedSwitchPattern

#cd quartus/max1000 && quartus_pgm -c Arrow-USB-Blaster -m JTAG jop.cdf
#cd ../..
#./down -e -c java/target/dist/bin/LedSwitchPattern.jop /dev/ttyUSB1

